###############################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

FROM flink:1.13.2-scala_2.12-java11

# Download connector libraries
RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/flink/flink-sql-connector-elasticsearch7_2.12/1.13.2/flink-sql-connector-elasticsearch7_2.12-1.13.2.jar; \
    wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/postgresql/postgresql/42.2.14/postgresql-42.2.14.jar;

# RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/hudi/hudi-utilities-bundle_2.12/0.8.0/hudi-utilities-bundle_2.12-0.8.0.jar; 
# RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/hudi/hudi-flink-bundle_2.12/0.8.0/hudi-flink-bundle_2.12-0.8.0.jar;
RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/commons-logging/commons-logging/1.2/commons-logging-1.2.jar;
RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar; 
# RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/hudi/hudi-client-common/0.8.0/hudi-client-common-0.8.0.jar; 
# RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/hadoop/hadoop-aws/2.9.2/hadoop-aws-2.9.2.jar; \ 
    # wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/com/amazonaws/aws-java-sdk-bundle/1.11.199/aws-java-sdk-bundle-1.11.199.jar; \ 
    # wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar; \ 
    # wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/hadoop/hadoop-common/2.9.2/hadoop-common-2.9.2.jar; \  
    # wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/hadoop/hadoop-hdfs/2.9.2/hadoop-hdfs-2.9.2.jar; \
    # wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar; 
# RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/org/apache/hudi/hudi-flink-bundle_2.12/0.9.0/hudi-flink-bundle_2.12-0.9.0.jar;
# RUN wget -P /opt/flink/lib/ https://maven.aliyun.com/repository/central/com/ververica/flink-connector-postgres-cdc/2.0.0/flink-connector-postgres-cdc-2.0.0.jar;
COPY jars/* /opt/flink/lib/

# Copy configuration
COPY conf/* /opt/flink/conf/